name: Report a working device
description: Report a device that works with this plugin

body:
  - type: input
    id: plugin-name
    attributes:
      label: Device Model
    validations:
      required: true
